/*
# copyright : Copyright (c) 2017-2024 Red Hat
# license   : GNU GFDL v1.3; see accompanying LICENSE file.
*/

	.file 1 "gap.S"
	.loc 1 1

	.text
	.global assembler_gap_test
assembler_gap_test:	
	.dc.l	0
	.dc.l	2

	.loc 1 2
	.dc.l	4
	.dc.l	6
	.dc.l	6
	.dc.l	6
	.dc.l	6
	.dc.l	6
	.dc.l	6
	.dc.l	6
	.dc.l	6
	.dc.l	6
	.dc.l	6
	.dc.l	6
	.dc.l	6
	.dc.l	6
	.dc.l	6
	.dc.l	6
	.dc.l	6
	.dc.l	6
	.dc.l	6
	.dc.l	6
	.dc.l	6
	.dc.l	6

	.global assembler_gap_end
assembler_gap_end:
	
